development:
  uri: "mongodb://localhost:27017/thegame_development"

test:
  uri: "mongodb://localhost:27017/thegame_test"

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL']  %>
